# Ajout des ID numériques au table DIMENSION dans seeds

In [2]:
import pandas as pd
import numpy as np
#import shutil

In [4]:
seeds_dir = '../snowflake/DBT/Projet_DBT/seeds'
src_data = '../pipeline/src/data'

In [3]:
#shutil.copytree(seeds_dir,'src_data',dirs_exist_ok=True)

'src_data'

### DIM_DOMAINES

In [7]:
df_domaines = pd.read_csv(src_data+"/DIM_DOMAINE.csv")
df_domaines = df_domaines.reset_index(names='ID')
df_domaines = df_domaines.set_index('ID')

In [8]:
df_domaines

    ID_DOMAINE                                                NOM
ID
0          A11                     Engins agricoles et forestiers
1          A12                  Espaces naturels et espaces verts
2          A13                     Etudes et assistance technique
3          A14                                         Production
4          A15                                  Soins aux animaux
..         ...                                                ...
105        N32  Personnel sédentaire du transport maritime et ...
106        N41         Personnel de conduite du transport routier
107        N42       Personnel d'encadrement du transport routier
108        N43          Personnel navigant du transport terrestre
109        N44  Personnel sédentaire du transport ferroviaire ...

[110 rows x 2 columns]

In [14]:
df_domaines.to_csv(src_data+'/DIM_DOMAINES.csv',encoding='utf-8')

### DIM_APPELLATIONS

In [10]:
df_appellations = pd.read_csv(src_data+"/DIM_APPELLATIONS.csv")
df_appellations = df_appellations.reset_index(names='id_appellation')
df_appellations = df_appellations.set_index('id_appellation')

In [11]:
df_appellations

       ID_APPELLATION                                                NOM
ID
0               10438           Agent / Agente de destruction d'insectes
1               10439   Agent / Agente de développement d'habitat social
2               10441              Agent / Agente de développement local
3               10442              Agent / Agente de développement rural
4               10444  Agent / Agente de diagnostic et d'intervention...
...               ...                                                ...
12102           17255  Opérateur / Opératrice presse pâte en industri...
12103           17259  Opérateur programmeur / Opératrice programmeus...
12104           17262  Opérateur qualifié / Opératrice qualifiée de m...
12105           17266  Opérateur régleur / Opératrice régleuse sur ch...
12106           17270    Opérateur régleur / Opératrice régleuse usinage

[12107 rows x 2 columns]

In [16]:
df_appellations.to_csv(src_data+'/DIM_APPELLATIONS.csv',encoding='utf-8')

### RAW_METIERS

In [18]:
df_metiers = pd.read_csv(src_data+"/RAW_METIERS.csv")
df_metiers = df_metiers.reset_index(names='id_metier')
df_metiers = df_metiers.set_index('id_metier')

In [19]:
df_metiers

,code_rome,libelle,code_appellation,code_domaine,libelle_search
ID_METIER,,,,,
0,A1101,Conducteur / Conductrice d'engins agricoles,404030,A11,Conducteur d'engins agricoles
1,A1101,Chauffeur / Chauffeuse de machines agricoles,11987,A11,Chauffeur de machines agricoles
2,A1101,Conducteur / Conductrice d'automoteur de récolte,38874,A11,Conducteur d'automoteur de récolte
3,A1101,Conducteur / Conductrice d'engins d'exploitati...,13254,A11,Conducteur d'engins d'exploitation agricole
4,A1101,Conducteur / Conductrice d'épareuse,38877,A11,Conducteur d'épareuse
...,...,...,...,...,...
12091,N4403,Opérateur / Opératrice de branchement du résea...,17064,N44,Opérateur de branchement du réseau ferré
12092,N4403,Opérateur / Opératrice de manœuvre du réseau f...,17119,N44,Opérateur de manœuvre du réseau ferré
12093,N4403,Opérateur / Opératrice de production du réseau...,17150,N44,Opérateur de production du réseau ferré
12094,N4403,Opérateur / Opératrice fret du réseau ferré,17231,N44,Opérateur fret du réseau ferré
12095,N4403,Opérateur / Opératrice triage du réseau ferré,17346,N44,Opérateur triage du réseau ferré

In [20]:
df_metiers.to_csv(src_data+'/RAW_METIERS.csv',encoding='utf-8')

### RAW_Softskills

In [21]:
df_softskill = pd.read_csv(src_data+"/RAW_SOFTSKILL.csv")
df_softskill = df_softskill.reset_index(names='id_softskill')
df_softskill = df_softskill.set_index('id_softskill')

In [22]:
df_softskill

,code_rome,uuid,created_at,skill_id,score,summary,details
ID_SOFTSKILLS,,,,,,,
0,A1101,ee359294-d429-4280-b1dc-7f426eab9d40,2025-04-30T11:41:12Z,soft_skill_19,1.000000,Réactivité,Répondre rapidement et de manière appropriée a...
1,A1101,ee359294-d429-4280-b1dc-7f426eab9d40,2025-04-30T11:41:12Z,soft_skill_11,1.000000,Être rigoureux,"Prêter attention aux détails, avoir le souci d..."
2,A1101,ee359294-d429-4280-b1dc-7f426eab9d40,2025-04-30T11:41:12Z,soft_skill_20,0.941106,Sens de l’analyse,"Examiner, décomposer et comparer les éléments ..."
3,A1101,ee359294-d429-4280-b1dc-7f426eab9d40,2025-04-30T11:41:12Z,soft_skill_09,0.573230,Sens de l’organisation,Avoir une propension à agencer et structurer s...
4,A1101,ee359294-d429-4280-b1dc-7f426eab9d40,2025-04-30T11:41:12Z,soft_skill_07,0.556641,Sens des responsabilités,"S’engager, avec discernement, dans une action ..."
...,...,...,...,...,...,...,...
13680,M1807,a8fe34f6-ff2c-4c9b-a42f-0a8d64712e3c,2025-04-30T12:01:02Z,soft_skill_02,0.145361,Sens de l’innovation/créativité,"Raisonner différemment, rechercher, imaginer, ..."
13681,M1807,a8fe34f6-ff2c-4c9b-a42f-0a8d64712e3c,2025-04-30T12:01:02Z,soft_skill_20,0.142835,Sens de l’analyse,"Examiner, décomposer et comparer les éléments ..."
13682,M1807,a8fe34f6-ff2c-4c9b-a42f-0a8d64712e3c,2025-04-30T12:01:02Z,soft_skill_03,0.139623,Capacité d’adaptation,"Faire face à la nouveauté et au changement, aj..."
13683,M1807,a8fe34f6-ff2c-4c9b-a42f-0a8d64712e3c,2025-04-30T12:01:02Z,soft_skill_18,0.100000,Faire preuve de diplomatie,"Être pondéré, nuancé, faire preuve de tact et ..."
13684,M1807,a8fe34f6-ff2c-4c9b-a42f-0a8d64712e3c,2025-04-30T12:01:02Z,soft_skill_16,0.073973,Sens des affaires et de la valeur de l’argent,Renvoie à la capacité d’empathie et d’analyse ...

In [23]:
df_softskill.to_csv(src_data+'/RAW_Softskills.csv',encoding='utf-8')

### STOPWORDS_FR

In [7]:
df_stopwords_fr = pd.read_csv(src_data+"/DIM_STOPWORDS.csv")
df_stopwords_fr = df_stopwords_fr.reset_index(names='id_word')
df_stopwords_fr = df_stopwords_fr.set_index('id_word')

In [8]:
df_stopwords_fr

               word
id_word
0                 a
1             abord
2        absolument
3              afin
4                ah
...             ...
686           étées
687            étés
688            êtes
689            être
690               ô

[691 rows x 1 columns]

In [9]:
df_stopwords_fr.to_csv(src_data+'/DIM_STOPWORDS.csv',encoding='utf-8')

### RAW_OFFRE

In [7]:
raw_offre = pd.read_csv(src_data+"/RAW_OFFRE.csv")
raw_offre = raw_offre.rename(columns={'id':'id_local'})
raw_offre = raw_offre.reset_index(names='id')
raw_offre = raw_offre.set_index('id')

/var/folders/tj/l36w8z3901ddy038kdl26mp80000gn/T/ipykernel_11186/3276077670.py:1: DtypeWarning: Columns (8,9,24) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_offre = pd.read_csv(src_data+"/RAW_OFFRE.csv")

In [14]:
raw_offre[raw_offre['is_handicap_accessible']==True]

,id_local,source,title,description,company_name,location_name,latitude,longitude,date_created,date_updated,...,category,sector,application_url,source_url,skills,remote_work,is_handicap_accessible,code_rome,langues,date_extraction
id,,,,,,,,,,,,,,,,,,,,,
26301,191CMYW,france_travail,Lead développeur/développeur sénior (H/F),"Nous croyons en l'importance de l'humain, de l...",GALAGO,12 - ONET LE CHATEAU,44.377987,2.562007,NaN,NaN,...,Développeur / Développeuse informatique,Conseil en relations publiques et communication,NaN,https://candidat.francetravail.fr/offres/reche...,Application web; Concevoir une application web,NaN,True,M1805,NaN,2025-05-01 20:08:57.881100
26394,190YJLG,france_travail,Programmateur d'activités (H/F),VOTRE FUTUR MÉTIER La programmation des interv...,ENEDIS,29 - GUIPAVAS,48.428236,-4.403555,NaN,NaN,...,Développeur / Développeuse informatique,Distribution d'électricité,NaN,https://candidat.francetravail.fr/offres/reche...,NaN,NaN,True,M1805,NaN,2025-05-01 20:08:57.881856
26662,189JDZW,france_travail,Technicien Support Utilisateurs Métiers - Pari...,QUI SOMMES-NOUS ? Exponens c'est. Un groupe dy...,Exponens,75 - Paris 12e Arrondissement,48.833494,2.415411,NaN,NaN,...,Développeur / Développeuse informatique,Activités comptables,https://jobaffinity.fr/apply/a8388nlrigot14cib...,https://candidat.francetravail.fr/offres/reche...,Application web; Concevoir une application web,NaN,True,M1805,NaN,2025-05-01 20:08:57.884117
27173,191LTLW,france_travail,Proxi Product Owner (H/F),L'entreprise : APF Entreprises 64 est une entr...,APF FRANCE HANDICAP,31 - TOULOUSE,43.604082,1.433805,NaN,NaN,...,Product Owner,Aide par le travail,NaN,https://candidat.francetravail.fr/offres/reche...,Analyser des données techniques pour optimiser...,NaN,True,M1806,Anglais,2025-05-01 20:09:03.607630
27811,191TFCR,france_travail,Administrateur de bases de données (H/F),Descriptif du poste : Vous êtes passionné(e) p...,HA PLUS PME,78 - TOUSSUS LE NOBLE,48.747331,2.111648,NaN,NaN,...,Administrateur / Administratrice de systèmes d...,Intermédiaires spécialisés dans le commerce d'...,NaN,https://candidat.francetravail.fr/offres/reche...,Administrer un système d'informations,NaN,True,M1801,Anglais,2025-05-01 20:09:06.767448
28117,191GCQX,france_travail,Administrateur systèmes et réseaux (H/F),Manpower TOULOUSE INFORMATIQUE recherche pour ...,MANPOWER FRANCE,31 - Toulouse,43.604082,1.433805,NaN,NaN,...,Administrateur / Administratrice de systèmes d...,Activités des agences de travail temporaire,NaN,https://candidat.francetravail.fr/offres/reche...,NaN,NaN,True,M1801,NaN,2025-05-01 20:09:06.770195
28140,191DNKT,france_travail,Administrateur de bases de données (H/F) - Guy...,AKTISEA est une entreprise adaptée spécialisée...,AKTISEA,78 - GUYANCOURT,48.772925,2.069679,NaN,NaN,...,Administrateur / Administratrice de systèmes d...,Activités de centres d'appels,NaN,https://candidat.francetravail.fr/offres/reche...,Administrer un système d'informations,NaN,True,M1801,NaN,2025-05-01 20:09:06.770380
28502,191KVMS,france_travail,Cartographe (H/F),Notre agence PROMAN TERTIAIRE INDUSTRIE recher...,PROMAN,33 - MERIGNAC,44.833370,-0.674682,NaN,NaN,...,Cartographe,Activités des agences de travail temporaire,https://www.proman-emploi.fr/?job=MP1006483&ca...,https://candidat.francetravail.fr/offres/reche...,NaN,NaN,True,M1808,NaN,2025-05-01 20:09:07.401051
28534,190YHSG,france_travail,Géomaticien (H/F),VOTRE FUTUR MÉTIER Au coeur d'une équipe agile...,ENEDIS,29 - BREST,48.406435,-4.497736,NaN,NaN,...,Cartographe,Distribution d'électricité,NaN,https://candidat.francetravail.fr/offres/reche...,Formaliser des données cartographiques et les ...,NaN,True,M1808,NaN,2025-05-01 20:09:07.401517
28574,189QCCR,france_travail,2471 - Dessinateur DAO (H/F),"DSI est une entreprise adaptée, engagée dans l...",DSI-ILE DE FRANCE,78 - ELANCOURT,48.778591,1.959970,NaN,NaN,...,Cartographe,Services administratifs combinés de bureau,NaN,https://candidat.francetravail.fr/offres/reche...,Procédures d'appels d'offres; Utilisation de l...,NaN,True,M1808,NaN,2025-05-01 20:09:07.402441
29319,190YJVG,france_travail,Superviseur exploitation dépannage (H/F),"VOTRE FUTUR MÉTIER Véritable """"chef d'orchestr...",ENEDIS,29 - BREST,48.406435,-4.497736,NaN,NaN,...,Technicien / Technicienne informatique,Distribution d'électricité,NaN,https://candidat.francetravail.fr/offres/reche...,NaN,NaN,True,M1810,NaN,2025-05-01 20:09:11.968591
29481,190NVQM,france_travail,Technicien informatique réparation H/F (H/F),"Afin de renforcer notre équipe, nous rechercho...",PRINTERREA,28 - VERNOUILLET,48.720484,1.356113,NaN,NaN,...,Technicien / Technicienne informatique,Activités de conditionnement,NaN,https://candidat.francetravail.fr/offres/reche...,Diagnostiquer la nature et l'origine des incid...,NaN,True,M1810,NaN,2025-05-01 20:09:11.970396
29873,191TGWF,france_travail,Consultant SAGE LIGNE100 (H/F),Nous recherchons un Consultant Sage ou une Con...,PC 19,19 - ST VIANCE,45.208296,1.468976,NaN,NaN,...,Intégrateur / Intégratrice logiciels métiers,Conseil en systèmes et logiciels informatiques,NaN,https://candidat.francetravail.fr/offres/reche...,Systèmes d'information de gestion; Comptabilit...,NaN,True,M1813,NaN,2025-05-01 20:09:13.592541
30212,191RWJL,france_travail,Technicien de maintenance de nuit (H/F),Notre agence PROMAN INDUSTRIE recherche pour s...,PROMAN,33 - BORDEAUX,44.851895,-0.587877,NaN,NaN,...,Technicien / Technicienne réseaux informatique...,Activités des agences de travail temporaire,https://www.proman-emploi.fr/?job=MP1008722&ca...,https://candidat.francetravail.fr/offres/reche...,NaN,NaN,True,M1816,NaN,2025-05-01 20:09:15.276815
30309,191CHYD,france_travail,Technicien réseaux et cybersécurité (H/F),"HumainEA, cabinet de recrutement spécialisé da...",HUMAINEA,84 - SORGUES,44.010004,4.877015,NaN,NaN,...,Technicien / Technicienne réseaux informatique...,Activités des agences de placement de main-d'œ...,NaN,https://candidat.francetravail.fr/offres/reche...,Diagnostic de pannes réseau; Configurer et par...,NaN,True,M1816,NaN,2025-05-01 20:09:15.277904
31986,190XQBZ,france_travail,Ingénieur réseau H/F - Paris Bercy (75) (H/F),AKTISEA est une entreprise adaptée spécialisée...,AKTISEA,75 - Paris (Dept.),NaN,NaN,NaN,NaN,...,Ingénieur / Ingénieure systèmes et réseaux inf...,Activités de centres d'appels,NaN,https://candidat.francetravail.fr/offres/reche...,Concevoir et gérer un projet; Concevoir un log...,NaN,True,M1822,NaN,2025-05-01 20:09:24.446166
32080,4786793,france_travail,Ingénieur Système Linux H/F,POSTE : Ingénieur Système Linux H/F DESCRIPTIO...,HumainEA,13 - MARSEILLE 01,43.282000,5.405000,NaN,NaN,...,Ingénieur / Ingénieure systèmes et réseaux inf...,Autre mise à disposition de ressources humaines,NaN,https://candidat.francetravail.fr/offres/reche...,NaN,NaN,True,M1822,NaN,2025-05-01 20:09:24.447134
33202,187SYLJ,france_travail,2426 - PMO junior - Domaine HSE (H/F),"***à compétences égales, priorité aux demandeu...",DISTRIBUTION SERVICES INDUSTRIELS,31 - TOULOUSE,43.604082,1.433805,NaN,NaN,...,Chef de projet / Cheffe de projet (Project Man...,Autre imprimerie (labeur),NaN,https://candidat.francetravail.fr/offres/reche...,Analyser des données techniques pour optimiser...,NaN,True,M1828,Anglais,2025-05-01 20:09:29.441092
33240,191GJRB,france_travail,ADMINISTRATEUR RESEAUX ET SYSTEMES SSII H/F (H/F),** Poste réservé aux personnes titulaires d'un...,HANDI INTERIM & RECRUTEMENT,86 - ST BENOIT,46.551622,0.347398,NaN,NaN,...,Administrateur / Administratrice réseaux - tél...,Activités des agences de travail temporaire,NaN,https://candidat.francetravail.fr/offres/reche...,Administrer un système d'informations,NaN,True,M1830,NaN,2025-05-01 20:09:29.785697
33570,191TDDH,france_travail,Senior Data Analyst (H/F) - Paris (75) (H/F),AKTISEA est une entreprise adaptée spécialisée...,AKTISEA,75 - PARIS 17,48.887702,2.304844,NaN,NaN,...,Chargé / Chargée d'études socio-économiques,Activités de centres d'appels,NaN,https://candidat.francetravail.fr/offres/reche...,Adapter les outils de traitement statistique d...,NaN,True,M1403,NaN,2025-05-01 20:09:35.943370
33965,191KBSX,france_travail,"Gestionnaire données Sparx (H/F), cadre, angla...",Nos Commandantes de Bord vous expliquent pourq...,CRIT INTERIM,31 - Blagnac,43.637457,1.382800,NaN,NaN,...,Chargé / Chargée d'études socio-économiques,Activités des agences de travail temporaire,NaN,https://candidat.francetravail.fr/offres/reche...,NaN,NaN,True,M1403,Anglais,2025-05-01 20:09:35.948322

In [9]:
raw_offre.to_csv(src_data+'/RAW_OFFRE.csv',encoding='utf-8')